# Generated by Django 5.1.2 on 2024-10-18 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('id',), 'verbose_name': 'Карзина', 'verbose_name_plural': 'Карзина'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart',
        ),
    ]
